### ISSUE TITLE
QA: Tại sao địa chỉ Bitcoin là hash của public key? Sao không dùng trực tiếp public key?

### ISSUE THREAD

**Issue by anhldbk** [vietnam-blockchain-experts/blockchain-doc#1]
Addresses are Derived from Public Keys, Which are Themselves Derived from Private Keys. More details are in this [link](https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses)

Technically, Bitcoin addresses and their checksums are constructed from the public key by a using repeated hashing with SHA256 and RIPEMD160.

Here are things worth to clarify:

#### Bitcoin addresses help compress public keys by half

It's just to get shorter addresses. Regular public keys are 65 bytes long, which is much too long to be convenient. Compressed public keys are 33 bytes and could potentially be used instead of hashes, though these are a little longer than 20-byte hashes. It also seems likely that Satoshi didn't know about compressed public keys or wasn't comfortable with using them when he designed Bitcoin.

#### Help to protect us from some security issues ?

- Hashes seem to help against certain attacks (some attacks against ECDSA, for example), though they also open up the possibility of other attacks (such as attacks against RIPEMD-160). It's not clear to me that they do improve security overall.
- I have read that there is no known algorithm that would allow public keys to be derived from public addresses within a practicable timescale, even with quantum computing. However, the same is not true for deriving private keys from public keys. Thus addresses that have not been used to spend, have benefits in terms of being more QC proof. I recall Vitalik Buterin writing on this topic.

#### Algorithms for generating keys may be weak & insecure
- A few days ago a severe vulnerability in the Android implementation of the Java SecureRandom random number generator was discovered. The result of this vulnerability is that private keys used in transactions on Android devices can be determined. All bitcoins in addresses used on Android devices need to be immediately rotated to a new address.

#### More about ECDSA

**Elliptic curves and ECDSA in particular are also used in messaging and systems security.** In Apple’s recent white paper on iOS security, they relayed how they use ECDSA extensively in the Apple ecosystem. Messages through iMessage are signed with ECDSA and iCloud keychain syncing relies on ECDSA. More and more technologies are using ECDSA for security, including end-to-end encrypted messaging services TextSecure and CryptoCat.

Why is ECDSA the algorithm of choice for new protocols when RSA is available and has been the gold standard for asymmetric cryptography since 1977? It boils down to the fact that we are better at breaking RSA than we are at breaking ECC.

As we described in a previous blog post, the security of a key depends on its size and its algorithm. Some algorithms are easier to break than others and require larger keys for the same level of security. Breaking an RSA key requires you to factor a large number. We are pretty good at factoring large numbers and getting better all the time. Breaking an ECDSA key requires you to solve the Elliptic Curve Discrete Logarithm Problem (ECDLP). The mathematical community has not made any major progress in improving algorithms to solve this problem since is was independently introduced by Koblitz and Miller in 1985.

**This means that with ECDSA you can get the same level of security as RSA but with smaller keys.** Smaller keys are better than larger keys for several reasons. Smaller keys have faster algorithms for generating signatures because the math involves smaller numbers. Smaller public keys mean smaller certificates and less data to pass around to establish a TLS connection. This means quicker connections and faster loading times on websites.
According to the ECRYPT II recommendations on key length, a 256-bit elliptic curve key provides as much protection as a 3,248-bit asymmetric key. Typical RSA keys in website certificates are 2048-bits. If we compare the portion of the TLS handshake that happens on the server for 256-bit ECDSA keys against the cryptographically much weaker 2048-bit RSA keys we get the following:

#### Reference
- [Six Things Bitcoin Users Should Know about Private Keys](http://bitzuma.com/posts/six-things-bitcoin-users-should-know-about-private-keys/)
- [Why are Bitcoin addresses hashes of public keys?](http://bitcoin.stackexchange.com/questions/3600/why-are-bitcoin-addresses-hashes-of-public-keys)
- [55 BTC Stolen Through Security Vulnerability in Android Bitcoin Wallets](https://web.archive.org/web/20160112180528/https://tradeblock.com/blog/security-vulnerability-in-all-android-bitcoin-wallets/)
- [ECDSA: The digital signature algorithm of a better internet](https://blog.cloudflare.com/ecdsa-the-digital-signature-algorithm-of-a-better-internet/)

**Comment by anhldbk** [comment]
A few days ago a severe vulnerability in the Android implementation of the Java SecureRandom random number generator was discovered. The result of this vulnerability is that private keys used in transactions on Android devices can be determined. All bitcoins in addresses used on Android devices need to be immediately rotated to a new address.

Reference: [55 BTC Stolen Through Security Vulnerability in Android Bitcoin Wallets](https://web.archive.org/web/20160112180528/https://tradeblock.com/blog/security-vulnerability-in-all-android-bitcoin-wallets/)

**Comment by anhldbk** [comment]
I've found a pretty good explanation at [What's the difference between public key and public address?](https://www.reddit.com/r/Bitcoin/comments/3filud/whats_the_difference_between_public_key_and/+&cd=2&hl=en&ct=clnk&gl=vn)

> The next thing to know is about public and private keys. Whether it's elliptic curves or RSA, the general idea is the same. You have a "private key" from which you can derive your public key. People can encrypt things to your public key, and if they do so, then only your private key can decrypt them. So you can publish your public key publicly, and people can then encrypt messages that can only be unlocked with your private key. A second feature of private/public keys is digital signatures. A signature is something that can only be created by your private key, but which your public key can be used to verify that the signature indeed must have been created with your private key. So I can use my private key to "sign" a PDF document for example, and if you have my public key and the document and the signature text, you can verify that indeed I made that signature for that document, and I made it with my private key. The signature proves I own the private key, even though it doesn't reveal the private key to you or anybody else.

> The most common way to send bitcoins is to an address, which is a hash of a Bitcoin public key. The reason we do it that way is so that if there is a vulnerability in elliptic curves, your money can still be safe, since the public key isn't even known until you spend the money, only the hash is known. The public key is revealed only when you spend money, because it is necessary to prove that the digital signature came from your private key. And the way Bitcoin verifies that the transaction is valid is it checks the signature with the public key (and the data being signed is not a PDF but the Bitcoin transaction itself), and the Bitcoin miners and users verify that the private key indeed did make that signature (and make it for this transaction), and then they also verify that the public key hash is the same hash as the output transaction. If those two things are true - the signature is good and the hash matches - then the transaction is valid and the money can be spent.

**Comment by LongNguyenHoang89** [comment]
Simple explanation:

Bitcoin address is the "Identity" of the wallet. In order to be considered as a valid identifier, a value needs to be unique. There are mainly 2 ways to create such identity:

1. Use a trusted-central server which generates "Identity" and map it to user to make sure there is no duplication. Bitcoin is pure decentralized so this method does not work.

2. Generate a random number in a range between 0 and a very big number N. N should be big enough so that there is very hard to have a collision even when there are multiple generation process running at the same time. 2^160 is a big enough N so that the output of RIPEMD-160 can be used. 

It is true that bigger N can be used (the public key itself). However, we want to keep the transaction size is as small as possible to increase system performance. RIPEMD-160 is used because it produces the shortest hashes which is sufficient to be collision-resistant.

**Comment by vuhung** [comment]
@anhldbk : Dùng hình giải thích dễ hiểu hơn là text :)

**Comment by anhldbk** [comment]
@vuhung : Em đang tập hợp một số key point của Blockchain để raise issue, viết doc (tiếng Việt) thôi anh. Em với bạn Trần Huy Vũ đang bàn giải pháp để đẩy community lên. Việc viết doc em nghĩ rất tốt, giúp cho mọi người cùng biết. Bên cạnh đó cũng cần những code example.

**Comment by anhldbk** [comment]
@LongNguyenHoang89 Cảm ơn bạn. Chắc là sẽ vẫn phải bổ sung vấn đề là: tương lai ECDSA có thể có vulnerability nhỉ? Mình sẽ đóng issue ở đây. Tạm thời mình đang tạo các issue liên quan tới các vấn đề của blockchain, để tiện viết tài liệu sau này. 

Mình thấy bạn khá quan tâm tới Blockchain. Tích cực đóng góp ý kiến nhé! Warmly welcome.
